/*
 This file belongs to the Servoy development and deployment environment, Copyright (C) 1997-2012 Servoy BV

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License along
 with this program; if not, see http://www.gnu.org/licenses or write to the Free
 Software Foundation,Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 */

package com.servoy.mobile.client.scripting;

import java.util.ArrayList;
import java.util.List;

import org.timepedia.exporter.client.Export;
import org.timepedia.exporter.client.Exportable;

import com.servoy.mobile.client.FormController;
import com.servoy.mobile.client.FormManager;

@Export
public class JSHistory implements Exportable
{
	private final FormManager formManager;
	private final List<FormController> historyList = new ArrayList<FormController>();
	private int historyIndex = -1;

	public JSHistory(FormManager formManager)
	{
		this.formManager = formManager;
		// this breaks gwt application, have to see how to fix it
		//export(ExporterUtil.wrap(this));
	}


	public void back()
	{
		if (historyIndex > 0)
		{
			int history = historyIndex - 1;
			historyIndex = -2;
			formManager.showForm(historyList.get(history));
			historyIndex = history;
		}
	}

	public void forward()
	{
		if (historyIndex < historyList.size() - 1)
		{
			int history = historyIndex + 1;
			historyIndex = -2;
			formManager.showForm(historyList.get(history));
			historyIndex = history;
		}
	}

	public void clear()
	{
		this.formManager.removeAllForms();
		historyIndex = -1;
		historyList.clear();
	}

	// This export does overwrite the default window history object!
//	private final native void export(Object object)
//	/*-{
//		$wnd.history = object;
//	}-*/;


	/**
	 * @param page
	 */
	public void add(FormController page)
	{
		if (historyIndex == -2) return; // skip, generated by itself.
		while (historyList.size() - 1 > historyIndex)
		{
			historyList.remove(historyIndex + 1);
		}
		historyIndex = historyList.size();
		historyList.add(page);

	}
}